name: "Setup Environment"

description: "Setup build environment and NodeJS"

runs:
  using: "composite"
  steps:
    - name: Setup Node environment
      uses: actions/setup-node@v6.3.0
      with:
        node-version-file: '.nvmrc'
    - name: Cache NodeJS dependencies
      uses: actions/cache@v5.0.5
      id: nodejs-cache
      with:
        path: js/node_modules
        key: ${{ runner.os }}-${{ runner.arch }}-npm-${{ hashFiles('js/package-lock.json') }}
    - name: Install NodeJS dependencies
      shell: bash
      if: ${{ steps.nodejs-cache.outputs.cache-hit != 'true' }}
      run: cd js && npm ci
