const { reverseObject } = require('../helpers');

const UNITS = {
    'ft': ['f', 'ft', `'`, 'feet'],
    'm': ['m', 'm.', 'meter', 'meters'],
    'in': ['in', 'inch', 'inches', '"', 'ins', 'inus'],
    'mm': ['mm'],
    'ohmm': ['ohmm', 'ohm.m', 'ohm-'],
    'gAPI': ['gapi'],
    'ft3/ft3': ['cfcf'],
    'pu': ['pu'],
    'lbf': ['lbf'],
    'C': ['degc'],
    'F': ['degf'],
    'K': ['degk'],
    'mD': ['md'],
    'g/cm3': ['g/c3', 'g/cc', 'g/cm3'],
    'g/m3': ['gm/3', 'gm/c'],
    'lbm/gal': ['ppg', 'lb/g', 'lbm/gal'],
    'ppm': ['ppm'],
    'mV': ['mv'],
    'ft/s': ['ft/s'],
    'ft/h': ['ft/h'],
    'ft/min': ['ft/min'],
    'knot': ['knot'],
    'kph': ['kph'],
    'm/h': ['m/h'],
    'm/s': ['m/s'],
    'm/min': ['m/min'],
    'mph': ['mph'],
    'kPa': ['kPa'],
    'psi': ['psi'],
    'bar': ['bar'],
    'us/ft': ['us/f', 'us/ft'],
    'us/m': ['us/m'],
    '': ['none'],
    'arcmin': ['arcmin'],
    'arcsec': ['arcsec'],
    'deg': ['deg'],
    'grad': ['grad'],
    'rad': ['rad'],
    'dp100f': ['dp100f'],
    'dp30m': ['dp30m'],
    'dpf': ['dpf'],
    'dpm': ['dpm'],
    '1/s': ['1/s'],
    'dega/h': ['dega/h'],
    'dega/m': ['dega/m'],
    'dega/s': ['dega/s'],
    'radsec': ['radsec'],
    'rev/s': ['rev/s'],
    'rph': ['rph'],
    'rpm': ['rpm'],
    'ac': ['ac'],
    'cm2': ['cm2'],
    'ft2': ['ft2'],
    'ha': ['ha'],
    'in2': ['in2'],
    'km2': ['km2'],
    'm2': ['m2'],
    'mi2': ['mi2'],
    'mm2': ['mm2'],
    'yd2': ['yd2'],
    'A': ['A'],
    'mA': ['mA'],
    'N': ['N'],
    'daN': ['daN'],
    'kdaN': ['kdaN'],
    'klbf': ['klbf'],
    'in/rev': ['in/rev'],
    'mm/rev': ['mm/rev'],
    'g': ['g'],
    'kg': ['kg'],
    'lb': ['lb'],
    'mcg': ['mcg'],
    'mg': ['mg'],
    'oz': ['oz'],
    'ton': ['ton'],
    'g/h': ['g/h'],
    'g/min': ['g/min'],
    'g/s': ['g/s'],
    'kg/h': ['kg/h'],
    'kg/min': ['kg/min'],
    'kg/s': ['kg/s'],
    'lb/h': ['lb/h'],
    'lb/min': ['lb/min'],
    'lb/s': ['lb/s'],
    'mcg/h': ['mcg/h'],
    'mcg/min': ['mcg/min'],
    'mcg/s': ['mcg/s'],
    'mg/h': ['mg/h'],
    'mg/min': ['mg/min'],
    'mg/s': ['mg/s'],
    'oz/h': ['oz/h'],
    'oz/min': ['oz/min'],
    'oz/s': ['oz/s'],
    'ton/h': ['ton/h'],
    'ton/min': ['ton/min'],
    'ton/s': ['ton/s'],
    'kg-m': ['kg-m'],
    'klb-ft': ['klb-ft'],
    'lb-ft': ['lb-ft'],
    'MPa': ['MPa'],
    'Pa': ['Pa'],
    'dsf': ['dsf'],
    'hPa': ['hpa'],
    'hsf': ['hsf'],
    'kPaAdjusted': ['kPaadjusted'],
    'ksi': ['ksi'],
    'ksiAdjusted': ['ksiAdjusted'],
    'psf': ['psf'],
    'psiAdjusted': ['psiAdjusted'],
    'torr': ['torr'],
    'Tbs': ['Tbs'],
    'bbl': ['bbl'],
    'cl': ['cl'],
    'cm3': ['cm3'],
    'cup': ['cup'],
    'dl': ['dl'],
    'fl-oz': ['fl-oz'],
    'ft3': ['ft3'],
    'gal': ['gal'],
    'glas': ['glas'],
    'in3': ['in3'],
    'kanna': ['kanna'],
    'kkp': ['kkp'],
    'km3': ['km3'],
    'krm': ['krm'],
    'I': ['I'],
    'm3': ['m3'],
    'ml': ['ml'],
    'mm3': ['mm3'],
    'msk': ['msk'],
    'pnt': ['pnt'],
    'qt': ['qt'],
    'tsk': ['tsk'],
    'tsp': ['tsp'],
    'yd3': ['yd3'],
    'Tbs/s': ['Tbs/s'],
    'bbl/h': ['bbl/h'],
    'bbl/min': ['bbl/min'],
    'bbl/s': ['bbl/s'],
    'cl/s': ['cl/s'],
    'cm3/s': ['cm3/s'],
    'cup/s': ['cup/s'],
    'dl/s': ['dl/s'],
    'fl-oz/h': ['fl-oz/h'],
    'fl-oz/min': ['fl-oz/min'],
    'fl-oz/s': ['fl-oz/s'],
    'ft3/h': ['ft3/h'],
    'ft3/min': ['ft3/min'],
    'ft3/s': ['ft3/s'],
    'gal/h': ['gal/h'],
    'gal/min': ['gal/min'],
    'gal/s': ['gal/s'],
    'in3/h': ['in3/h'],
    'in3/min': ['in3/min'],
    'in3/s': ['in3/s'],
    'kl/h': ['kl/h'],
    'kl/min': ['kl/min'],
    'kl/s': ['kl/s'],
    'km3/s': ['km3/s'],
    'I/h': ['I/h'],
    'I/min': ['I/min'],
    'I/s': ['I/s'],
    'm3/h': ['m3/h'],
    'm3/min': ['m3/min'],
    'm3/s': ['m3/s'],
    'ml/s': ['ml/s'],
    'mm3/s': ['mm3/s'],
    'pnt/h': ['pnt/h'],
    'pnt/min': ['pnt/min'],
    'pnt/s': ['pnt/s'],
    'qt/s': ['qt/s'],
    'tsp/s': ['tsp/s'],
    'yd3/h': ['yd3/h'],
    'yd3/min': ['yd3/min'],
    'yd3/s': ['yd3/s'],
    'hp': ['hp'],
    'mhp': ['mhp'],
    'watt': ['watt'],
    'i-bar': ['i-bar'],
    'i-kPa': ['i-kPa'],
    'i-ksi': ['i-ksi'],
    'i-pa': ['i-pa'],
    'i-psi': ['i-psi'],
    'kPa/m': ['kPa/m'],
    'psi/ft': ['psi/ft'],
    'rpg': ['rpg'],
    'rpl': ['rpl'],
    'd': ['d'],
    'h': ['h'],
    'min': ['min'],
    'month': ['month'],
    'ms': ['ms'],
    'mu': ['mu'],
    'ns': ['ns'],
    's': ['s'],
    'week': ['week'],
    'year': ['year'],
    'J': ['J'],
    'Nm': ['Nm'],
    'ft-klbf': ['ft-klbf'],
    'ft-lbf': ['ft-lbf'],
    'kNm': ['kNm'],
    'V': ['V'],
    'gal/Mgal': ['gal/Mgal'],
    'I/m3': ['I/m3'],
    'cm': ['cm'],
    'km': ['km'],
    'mi': ['mi'],
    'yd': ['yd'],
    'Sg': ['Sg'],
    'g/l': ['g/l'],
    'kg/cm3': ['kg/cm3'],
    'kg/m3': ['kg/m3'],
    'lb/Mgal': ['lb/Mgal'],
    'lb/ft3': ['lb/ft3'],
    'lb/gal': ['lb/gal'],
    'lb/in3': ['lb/in3'],
    'ppg': ['ppg'],
};

const BUCKETS = {
    'Angle': [...UNITS.arcmin, ...UNITS.arcsec, ...UNITS.deg, ...UNITS.grad, ...UNITS.rad],
    'Angle Per Length': [...UNITS.dp100f, ...UNITS.dp30m, ...UNITS.dpf, ...UNITS.dpm],
    'Anglular Velocity': [
        ...UNITS['1/s'],
        ...UNITS['dega/h'],
        ...UNITS['dega/m'],
        ...UNITS['dega/s'],
        ...UNITS.radsec,
        ...UNITS['rev/s'],
        ...UNITS.rph,
        ...UNITS.rpm,
    ],
    'Area': [
        ...UNITS.ac,
        ...UNITS.cm2,
        ...UNITS.ft2,
        ...UNITS.ha,
        ...UNITS.in2,
        ...UNITS.km2,
        ...UNITS.m2,
        ...UNITS.mi2,
        ...UNITS.mm2,
        ...UNITS.yd2,
    ],
    'Current': [...UNITS.A, ...UNITS.mA],
    'Force': [...UNITS.N, ...UNITS.daN, ...UNITS.kdaN, ...UNITS.klbf, ...UNITS.lbf],
    'Length Per Angle': [...UNITS['in/rev'], ...UNITS['mm/rev']],
    'Mass': [
        ...UNITS.g,
        ...UNITS.kg,
        ...UNITS.lb,
        ...UNITS.mcg,
        ...UNITS.mg,
        ...UNITS.oz,
        ...UNITS.ton,
    ],
    'Mass Flow Rate': [
        ...UNITS['g/h'],
        ...UNITS['g/min'],
        ...UNITS['g/s'],
        ...UNITS['kg/h'],
        ...UNITS['kg/min'],
        ...UNITS['kg/s'],
        ...UNITS['lb/h'],
        ...UNITS['lb/min'],
        ...UNITS['lb/s'],
        ...UNITS['mcg/h'],
        ...UNITS['mcg/min'],
        ...UNITS['mcg/s'],
        ...UNITS['mg/h'],
        ...UNITS['mg/min'],
        ...UNITS['mg/s'],
        ...UNITS['oz/h'],
        ...UNITS['oz/min'],
        ...UNITS['oz/s'],
        ...UNITS['ton/h'],
        ...UNITS['ton/min'],
        ...UNITS['ton/s'],
    ],
    'Mass per length': [...UNITS['kg-m'], ...UNITS['klb-ft'], ...UNITS['lb-ft']],
    'Volume Flow Rate': [
        ...UNITS['Tbs/s'],
        ...UNITS['bbl/h'],
        ...UNITS['bbl/min'],
        ...UNITS['bbl/s'],
        ...UNITS['cl/s'],
        ...UNITS['cm3/s'],
        ...UNITS['cup/s'],
        ...UNITS['dl/s'],
        ...UNITS['fl-oz/h'],
        ...UNITS['fl-oz/min'],
        ...UNITS['fl-oz/s'],
        ...UNITS['ft3/h'],
        ...UNITS['ft3/min'],
        ...UNITS['ft3/s'],
        ...UNITS['gal/h'],
        ...UNITS['gal/min'],
        ...UNITS['gal/s'],
        ...UNITS['in3/h'],
        ...UNITS['in3/min'],
        ...UNITS['in3/s'],
        ...UNITS['kl/h'],
        ...UNITS['kl/min'],
        ...UNITS['kl/s'],
        ...UNITS['km3/s'],
        ...UNITS['I/h'],
        ...UNITS['I/min'],
        ...UNITS['I/s'],
        ...UNITS['m3/h'],
        ...UNITS['m3/min'],
        ...UNITS['m3/s'],
        ...UNITS['ml/s'],
        ...UNITS['mm3/s'],
        ...UNITS['pnt/h'],
        ...UNITS['pnt/min'],
        ...UNITS['pnt/s'],
        ...UNITS['qt/s'],
        ...UNITS['tsp/s'],
        ...UNITS['yd3/h'],
        ...UNITS['yd3/min'],
        ...UNITS['yd3/s'],
    ],
    'Power': [...UNITS.hp, ...UNITS.mhp, ...UNITS.watt],
    'Inverse Pressure': [
        ...UNITS['i-bar'],
        ...UNITS['i-kPa'],
        ...UNITS['i-ksi'],
        ...UNITS['i-pa'],
        ...UNITS['i-psi'],
    ],
    'Pressure Gradient': [...UNITS['kPa/m'], ...UNITS['psi/ft']],
    'Revolution Per Volume': [...UNITS.rpg, ...UNITS.rpl],
    'Time': [
        ...UNITS.d,
        ...UNITS.h,
        ...UNITS.min,
        ...UNITS.month,
        ...UNITS.ms,
        ...UNITS.mu,
        ...UNITS.ns,
        ...UNITS.s,
        ...UNITS.week,
        ...UNITS.year,
    ],
    'Torque': [...UNITS.J, ...UNITS.Nm, ...UNITS['ft-klbf'], ...UNITS['ft-lbf'], ...UNITS.kNm],
    'Voltage': [...UNITS.V, ...UNITS.mV],
    'Volume Concentration': [...UNITS['gal/Mgal'], ...UNITS['I/m3']],
    'Length': [...UNITS.m, ...UNITS.ft, ...UNITS.km, ...UNITS.m, ...UNITS.mi, ...UNITS.yd],
    'Gamma': [...UNITS.gAPI],
    'Resistivity': [...UNITS.ohmm],
    'Formation Density': [...UNITS['g/cm3']],
    'Density': [
        ...UNITS.Sg,
        ...UNITS['kg/cm3'],
        ...UNITS['kg/m3'],
        ...UNITS['lb/Mgal'],
        ...UNITS['lb/ft3'],
        ...UNITS['lb/gal'],
        ...UNITS['lb/in3'],
        ...UNITS.ppg,
    ],
    'Porosity': [...UNITS['ft3/ft3'], ...UNITS.pu],
    'Permiability': [...UNITS.mD],
    'Acoustic Slowness': [...UNITS['us/ft'], ...UNITS['us/m']],
    'Temperature': [...UNITS.C, ...UNITS.F, ...UNITS.K],
    'Short Length': [...UNITS.mm, ...UNITS.in, ...UNITS.cm],
    'Concentration': [...UNITS.ppm],
    'Velocity': [
        ...UNITS['m/s'],
        ...UNITS['ft/s'],
        ...UNITS['ft/h'],
        ...UNITS['ft/min'],
        ...UNITS.knot,
        ...UNITS.kph,
        ...UNITS['m/h'],
        ...UNITS['m/min'],
        ...UNITS['m/s'],
        ...UNITS.mph,
    ],
    'Volume': [
        ...UNITS.Tbs,
        ...UNITS.bbl,
        ...UNITS.cl,
        ...UNITS.cm3,
        ...UNITS.cup,
        ...UNITS.dl,
        ...UNITS['fl-oz'],
        ...UNITS.ft3,
        ...UNITS.gal,
        ...UNITS.glas,
        ...UNITS.in3,
        ...UNITS.kanna,
        ...UNITS.kkp,
        ...UNITS.km3,
        ...UNITS.krm,
        ...UNITS.I,
        ...UNITS.m3,
        ...UNITS.ml,
        ...UNITS.mm3,
        ...UNITS.msk,
        ...UNITS.pnt,
        ...UNITS.qt,
        ...UNITS.tsk,
        ...UNITS.tsp,
        ...UNITS.yd3,
    ],
    'Mse Pressure': [...UNITS.kPa, ...UNITS.ksi],
    'Pressure': [
        ...UNITS.bar,
        ...UNITS.psi,
        ...UNITS.MPa,
        ...UNITS.Pa,
        ...UNITS.bar,
        ...UNITS.dsf,
        ...UNITS.hPa,
        ...UNITS.kPaAdjusted,
        ...UNITS.ksiAdjusted,
        ...UNITS.psf,
        ...UNITS.psi,
        ...UNITS.psiAdjusted,
        ...UNITS.torr,
    ],
    'Other': ['*'],
};

module.exports = {
    UNITS,
    UNIT_MAP: reverseObject(UNITS),
    BUCKETS,
    BUCKET_MAP: reverseObject(BUCKETS),
};
