name: 'Publish'

on:
  push:
    tags:
      - 'js@v*'
      - 'py@v*'
  workflow_dispatch:

jobs:
  publish-js:
    name: Publish JS
    if: startsWith(github.ref_name, 'js@v') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-24.04
    steps:
      - name: Load secrets from 1Password
        uses: 1password/load-secrets-action@v4.0.0
        id: secrets
        with:
          export-env: false
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN_RO }}
          PUBLISH_NPM_TOKEN_DEV: 'op://GitHub.Actions/NPM/PUBLISH_NPM_TOKEN_DEV'
      - name: Checkout sources
        uses: actions/checkout@v6
      - name: Setup Environment
        uses: ./.github/actions/setup-environment
      - name: Sync definitions
        run: bash scripts/sync-definitions.sh
      - name: Build
        run: cd js && npm run build
      - name: Publish
        uses: actions/github-script@v9
        env:
          TAG: '${{ github.ref_name }}'
          NPM_TOKEN: '${{ steps.secrets.outputs.PUBLISH_NPM_TOKEN_DEV }}'
          WORKING_DIRECTORY: 'js'
        with:
          script: |
            const {default: run} = await import(`${process.cwd()}/.github/scripts/publish.mjs`);
            await run({github, context, core, glob, io, exec, require});

  publish-py:
    name: Publish Python
    if: startsWith(github.ref_name, 'py@v')
    runs-on: ubuntu-24.04
    environment: pypi
    permissions:
      id-token: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Sync definitions
        run: bash scripts/sync-definitions.sh
      - name: Install build tools
        run: pip install build
      - name: Build
        run: cd py && python -m build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: py/dist/
