name: Release

on:
  push:
    branches:
      - master

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-24.04
    steps:
      - name: Load secrets from 1Password
        uses: 1password/load-secrets-action@v2.0.0
        id: secrets
        with:
          export-env: false
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN_RO }}
          #
          GH_ACTIONS_AUTOMATION: 'op://GitHub.Actions/GitHub/Tokens/GH_ACTIONS_AUTOMATION'
      - name: Release Please
        uses: googleapis/release-please-action@v4.2.0
        with:
          release-type: node
          target-branch: master
          # TODO: for some reason, this does not work with corva-bot
          token: ${{ steps.secrets.outputs.GH_ACTIONS_AUTOMATION }}
